Diplom2/Controllers/HomeController.cs
using Diplom2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using static Diplom2.Models.DB;
using Microsoft.Extensions.Configuration;
using System.Data;
using Microsoft.Data.SqlClient;

namespace Diplom2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public readonly IConfiguration _config;

        public HomeController(ILogger<HomeController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public IDbConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Catalog()
        {
            var model = GetPizzaNames();
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Diplom2/Controllers/PizzaController.cs
using Diplom2.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using static Diplom2.Models.DB;


namespace Diplom2.Controllers
{
    public class PizzaController : Controller
    {
        private Sample_pizzaContext db;
        private Sample_IngrContext db1;

        public PizzaController(Sample_pizzaContext context, Sample_IngrContext context1)
        {
            db1 = context1;
            db = context;
        }
        [HttpPost]
        public async Task<IActionResult> Save(string size, string part, string b, string id)
        {
            var pizza = GetPizza(int.Parse(id));
            double total_price = pizza[0].Price_pizza;
            var ssize = int.Parse(size);
            if (ssize == 1)
            {
                total_price = total_price / 2;
            }
            else if (ssize == 3)
            {
                total_price = total_price * 2;
            }
            var ppart = int.Parse(part);
            if (ppart == 3)
            {
                total_price = total_price * 0.75;
            }
            else if (ppart == 2)
            {
                total_price = total_price * 0.5;
            }
            else if (ppart == 1)
            {
                total_price = total_price * 0.25;
            }
            var ingr = GetIngr(int.Parse(id));
            List<int> ingrn = new List<int>();
            Regex regex = new Regex(@"\d*");
            MatchCollection matches = regex.Matches(b);
            if (matches.Count > 0)
            {
                foreach (Match match in matches)
                    if (!(match.Value == "")) { ingrn.Add(int.Parse(match.Value)); }
            }

            for (int i = 0; i < ingrn.Count; i++)
            {
                total_price = total_price - ingr[i].Price_ingr;
                var j = ingr[i].Price_ingr * ingrn[i];
                total_price = total_price + j;
            }
            
            var user_id = GetAuthUserId(User.Identity.Name);
            db.Sample_pizza.Add(new Sample_pizza { id_pizza = pizza[0].id, id_user = user_id, Part = ppart, Size = ssize, Price = total_price});
            await db.SaveChangesAsync();
            var samples = GetIdSample();
            for (int i = 0; i < ingr.Count; i++)
            {
                db1.Sample_Ingr.Add(new Sample_Ingr { id_sample = samples, id_ingr = ingr[i].id, Multilier = ingrn[i] });
            }
            await db1.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Pizza(int value)
        {
            ArrayList model = new ArrayList();
            model.Add(value);
            return View(model);
        }
        [HttpPost]
        public ActionResult Summa(string size, string part, string b, string id)
        {
            var pizza = GetPizza(int.Parse(id));
            double total_price = pizza[0].Price_pizza;
            var ssize = int.Parse(size);
            if(ssize == 1)
            {
                total_price = total_price / 2;
            }
            else if(ssize == 3)
            {
                total_price = total_price * 2;
            }
            var ppart = int.Parse(part);
            if(ppart == 3)
            {
                total_price = total_price * 0.75;
            }
            else if(ppart == 2)
            {
                total_price = total_price * 0.5;
            }
            else if (ppart == 1)
            {
                total_price = total_price * 0.25;
            }
            var ingr = GetIngr(int.Parse(id));
            List<int> ingrn = new List<int>();
            Regex regex = new Regex(@"\d*");
            MatchCollection matches = regex.Matches(b);
            if (matches.Count > 0)
            {
                foreach (Match match in matches)
                    if (!(match.Value == "")) { ingrn.Add(int.Parse(match.Value)); }
            }

            for (int i = 0; i < ingrn.Count; i++)
            {
                total_price = total_price - ingr[i].Price_ingr;
                var j = ingr[i].Price_ingr * ingrn[i];
                total_price = total_price + j;
            }
            return PartialView(total_price);
        }
    }
}

Diplom2/Views/Home/Catalog.cshtml
<h2>Каталог нашої смачної піци</h2>
@using System.Text.RegularExpressions;

@{var i = 0;}
<section class="text-center mb-4">
    @{var item = @Model;}
    @{for (i = 0; i < @Model.Count; i++)
        {
    <div class="row wow fadeIn">
            <div class="col-lg-3 col-md-6 mb-4">
                <img src="~/img/@item[i].id .png" height=200 width=200 />
                Номер: @item[i].id
                Назва: @item[i].Name
                Ціна: @item[i].Price_pizza
                @{ if (User.Identity.IsAuthenticated)
                    {<a asp-controller="Pizza" asp-action="Pizza" asp-route-value="@item[i].id">Шаблон</a>}
                    else
                    {<strong>Для замовлення зареєструйтесь</strong>}
                }
            </div>
        @{i++;}
        @if (i == Model.Count) { break; }
    <div class="col-lg-3 col-md-6 mb-4">
        <img src="~/img/@item[i].id .png" height=200 width=200 />
        Номер: @item[i].id
        Назва: @item[i].Name
        Ціна: @item[i].Price_pizza
        @{ if (User.Identity.IsAuthenticated)
            {<a asp-controller="Pizza" asp-action="Pizza" asp-route-value="@item[i].id">Шаблон</a>}
            else
            {<strong>Для замовлення зареєструйтесь</strong>}
        }
    </div>
        @{i++;}
        @if (i == Model.Count) { break; }
    <div class="col-lg-3 col-md-6 mb-4">
        <img src="~/img/@item[i].id .png" height=200 width=200 />
        Номер: @item[i].id
        Назва: @item[i].Name
        Ціна: @item[i].Price_pizza
        @{ if (User.Identity.IsAuthenticated)
            {<a asp-controller="Pizza" asp-action="Pizza" asp-route-value="@item[i].id">Шаблон</a>}
            else
            {<strong>Для замовлення зареєструйтесь</strong>}
        }
    </div>
        @{i++;}
        @if (i == Model.Count) { break; }
    <div class="col-lg-3 col-md-6 mb-4">
        <img src="~/img/@item[i].id .png" height=200 width=200 />
        Номер: @item[i].id
        Назва: @item[i].Name
        Ціна: @item[i].Price_pizza
        @{ if (User.Identity.IsAuthenticated)
            {<a asp-controller="Pizza" asp-action="Pizza" asp-route-value="@item[i].id">Шаблон</a>}
            else
            {<strong>Для замовлення зареєструйтесь</strong>}
        }
    </div>
    </div>};
    }
</section>

Diplom2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">
        Ласкаво просимо @{ if (User.Identity.IsAuthenticated)
            { @Diplom2.Models.DB.GetAuthUserName(User.Identity.Name) }
        }
    </h1>
    Піца (італ. pizza) — традиційна італійська страва, спочатку у вигляді круглого дріжджового коржика,
    що випікається з покладеною зверху начинкою з томатного соусу, сиру та часто інших інгредієнтів,
    таких як м'ясо, овочі, гриби та інші продукти. Невелику піцу іноді називають піцеттою. Кухар,
    який спеціалізується на приготуванні піци, – піцайоло.
</div>
<img src="~/img/pizza-03.jpg" />