Diplom2/Controllers/BaketController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using static Diplom2.Models.DB;

namespace Diplom2.Controllers
{
    public class BaketController : Controller
    {

        private BaketContext db;
        private BufferContext db1;
        private Baket_addContext db2;

        public BaketController(BaketContext context, BufferContext context1, Baket_addContext context2)
        {
            db2 = context2;
            db1 = context1;
            db = context;
        }
        public IActionResult Basket()
        {
            var model =GetAuthUserId(User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save(string b, string count, string sample)
        {
            double total_price = 0;
            var ccount = int.Parse(count);
            var ssample_id = int.Parse(sample);
            total_price = total_price + GetSamplesPriceById(ssample_id);
            total_price = total_price * ccount;
            var adds = GetAdd();
            List<int> addsn = new List<int>();
            Regex regex = new Regex(@"\d*");
            MatchCollection matches = regex.Matches(b);
            if (matches.Count > 0)
            {
                foreach (Match match in matches)
                    if (!(match.Value == "")) { addsn.Add(int.Parse(match.Value)); }
            }

            for (int i = 0; i < addsn.Count; i++)
            {
                var j = adds[i].Price_add * addsn[i];
                total_price = total_price + j;
            }
            var user_id = GetAuthUserId(User.Identity.Name);
            db.Baket.Add(new Baket { id_user = user_id, Price_baket = total_price });
            await db.SaveChangesAsync();
            var bakets = GetIdBaket();
            db1.Buffer.Add(new Diplom2.Models.DB.Buffer { id_baket = bakets, id_sample = ssample_id, Count = ccount });
            for (int i = 0; i < adds.Count; i++)
            {
                db2.Baket_add.Add(new Baket_add { id_baket = bakets, id_add = adds[i].id, Count = addsn[i] });
            }
            await db1.SaveChangesAsync();
            await db2.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Summa(string b, string count, string sample)
        {
            double total_price = 0;
            var ccount = int.Parse(count);
            var ssample_id = int.Parse(sample);
            total_price = total_price + GetSamplesPriceById(ssample_id);
            total_price = total_price * ccount;
            var ingr = GetAdd();
            List<int> ingrn = new List<int>();
            Regex regex = new Regex(@"\d*");
            MatchCollection matches = regex.Matches(b);
            if (matches.Count > 0)
            {
                foreach (Match match in matches)
                    if (!(match.Value == "")) { ingrn.Add(int.Parse(match.Value)); }
            }

            for (int i = 0; i < ingrn.Count; i++)
            {
                var j = ingr[i].Price_add * ingrn[i];
                total_price = total_price + j;
            }
            return PartialView(total_price);
        }
    }
}

Diplom2/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Diplom2.Models.DB;

namespace Diplom2.Controllers
{
    public class OrderController : Controller
    {
        private OrderContext db;

        public OrderController(OrderContext context)
        {
            db = context;
        }

        public IActionResult Order()
        {
            var model = GetAuthUserId(User.Identity.Name);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save(string id_baket, string adress, string data, string time)
        {
            var id_bakets = int.Parse(id_baket);
            time = " " + time;
            DateTime dataa = DateTime.Parse(data+time);
            var user_id = GetAuthUserId(User.Identity.Name);
            db.Order.Add(new Order { id_user = user_id, id_baket = id_bakets, Adress = adress, Data_in = dataa, Total_price = GetBaketPrice(id_bakets) });
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Diplom2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diplom2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery/dist/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OOO Pizza</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="Authorization">Авторизуватися\Вийти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Catalog">Каталог</a>
                        </li>
                        @{ if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="Register">Зареєструватися</a>
                                </li>

                            }
                        }
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-controller="Baket" asp-action="Basket">Кошик</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-controller="Order" asp-action="Order">Замовлення</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="UsersItems">Профіль</a>
                                </li>
                                if (Diplom2.Models.DB.GetUserData(Diplom2.Models.DB.GetAuthUserId(User.Identity.Name)).Admin == 1)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link active" aria-current="page" asp-controller="User" asp-action="AdminItems">Адмін</a>
                                    </li>
                                }
                            }

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OOO Pizza <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>